app = "bossgp-pocketbase"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8090"

[[mounts]]
  source = "pb_data"
  destination = "/app/pb_data"

[http_service]
  internal_port = 8090
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0
  processes = ["app"]
